name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt update && sudo apt-get install -y libcurl4-openssl-dev check
    - name: configure
      run: sh autogen.sh && ./configure
    - name: make
      run: make
    - name: maketest
      run: make test
